// app/layout.tsx
import React from "react";
import { Metadata } from "next";
import StoreProvider from "../components/StoreProvider";
import Container from "@/components/Container";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Layout raíz de la aplicación que envuelve toda la UI con el StoreProvider y Container.
 */
const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className="pt-2 px-10">
        <StoreProvider>
          <Container>{children}</Container>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
