
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import StoreProvider from './StoreProvider';
import { useSelector } from "react-redux";
import { RootState } from "@/redux/store";
import Container from "@/components/Container";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <StoreProvider>
          <Container>{children}</Container>
        </StoreProvider>
      </body>
    </html>
  );
}
